### ISSUE TITLE
Indexer model should extend Mage_Index_Model_Indexer_Abstract.

### ISSUE THREAD

**Issue by dylandepass** [EcomDev/EcomDev_UrlRewrite#10]
Hello,

First off, awesome extension! I was able to get it working and it created the url rewrites of 15,000 products in no time flat!! Miles ahead of the time it was taking before.

One thing I noticed though is when I turn on compilation I get the error below when I try to go to my admin panel. Any ideas on whats wrong?

Indexer model should extend Mage_Index_Model_Indexer_Abstract.

Trace:
#0 /home/nrml123s/public_html/includes/src/Mage_Index_Model_Process.php(310): Mage::throwException('Indexer model s...')
#1 /home/nrml123s/public_html/includes/src/Mage_Index_Block_Adminhtml_Notifications.php(41): Mage_Index_Model_Process->getIndexer()
#2 /home/nrml123s/public_html/app/design/adminhtml/default/default/template/index/notifications.phtml(27): Mage_Index_Block_Adminhtml_Notifications->getProcessesForReindex()
#3 /home/nrml123s/public_html/includes/src/__default.php(3205): include('/home/nrml123s/...')
#4 /home/nrml123s/public_html/includes/src/__default.php(3236): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#5 /home/nrml123s/public_html/includes/src/__default.php(3250): Mage_Core_Block_Template->renderView()
#6 /home/nrml123s/public_html/includes/src/Mage_Adminhtml_Block_Template.php(81): Mage_Core_Block_Template->_toHtml()
#7 /home/nrml123s/public_html/includes/src/Mage_Index_Block_Adminhtml_Notifications.php(67): Mage_Adminhtml_Block_Template->_toHtml()
#8 /home/nrml123s/public_html/includes/src/__default.php(2500): Mage_Index_Block_Adminhtml_Notifications->_toHtml()
#9 /home/nrml123s/public_html/includes/src/__default.php(12950): Mage_Core_Block_Abstract->toHtml()
#10 /home/nrml123s/public_html/includes/src/__default.php(2500): Mage_Core_Block_Text_List->_toHtml()
#11 /home/nrml123s/public_html/includes/src/__default.php(2219): Mage_Core_Block_Abstract->toHtml()
#12 /home/nrml123s/public_html/includes/src/__default.php(2163): Mage_Core_Block_Abstract->_getChildHtml('notifications', true)
#13 /home/nrml123s/public_html/app/design/adminhtml/default/default/template/page.phtml(55): Mage_Core_Block_Abstract->getChildHtml('notifications')
#14 /home/nrml123s/public_html/includes/src/__default.php(3205): include('/home/nrml123s/...')
#15 /home/nrml123s/public_html/includes/src/__default.php(3236): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#16 /home/nrml123s/public_html/includes/src/__default.php(3250): Mage_Core_Block_Template->renderView()
#17 /home/nrml123s/public_html/includes/src/Mage_Adminhtml_Block_Template.php(81): Mage_Core_Block_Template->_toHtml()
#18 /home/nrml123s/public_html/includes/src/__default.php(2500): Mage_Adminhtml_Block_Template->_toHtml()
#19 /home/nrml123s/public_html/includes/src/__default.php(26967): Mage_Core_Block_Abstract->toHtml()
#20 /home/nrml123s/public_html/includes/src/__default.php(13344): Mage_Core_Model_Layout->getOutput()
#21 /home/nrml123s/public_html/app/code/core/Mage/Adminhtml/controllers/DashboardController.php(43): Mage_Core_Controller_Varien_Action->renderLayout()
#22 /home/nrml123s/public_html/includes/src/__default.php(13373): Mage_Adminhtml_DashboardController->indexAction()
#23 /home/nrml123s/public_html/includes/src/__default.php(17629): Mage_Core_Controller_Varien_Action->dispatch('index')
#24 /home/nrml123s/public_html/includes/src/__default.php(17220): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#25 /home/nrml123s/public_html/includes/src/__default.php(19712): Mage_Core_Controller_Varien_Front->dispatch()
#26 /home/nrml123s/public_html/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#27 /home/nrml123s/public_html/index.php(80): Mage::run('', 'store')
#28 {main}

**Comment by IvanChepurnyi** [comment]
Why do you use compile feature? It actually outdated, if you want to get performance on the code, use apc with apc.stat property to 0.

**Comment by paales** [comment]
Alternatively you could use http://www.fabrizio-branca.de/magento-class-path-cache.html (backport of the Magento 2 implementation, sort of).
