### ISSUE TITLE
Missing value for product attribute "url_path"

### ISSUE THREAD

**Issue by jirizahradka** [EcomDev/EcomDev_UrlRewrite#13]
Hello,
we are using the EcomDev_UrlRewrite module, but there is a problem that product attribute url_path is not filled for new products. Thus it is still empty. I have checked the module sources and I know that it is caused by the EcomDev_UrlRewrite module. Where can I find url_path of the products?

**Comment by IvanChepurnyi** [comment]
Hi there,

This is actually is because of core implementation was modifying the product itself, that was a redundant action for url rewrites and one of the slowdowns in that module. You should retrieve url_path from core_url_rewrite tables related to the product.
