### ISSUE TITLE
Undefined class constant 'STRAIGHT_JOIN_ON'

### ISSUE THREAD

**Issue by davidalexander** [EcomDev/EcomDev_UrlRewrite#3]
Hi Ivan

Thanks for putting the effort into maintaining an bug fixing this.

The extension installs fine, however, upon running the 'catalog_url' reindex the following exception occurs:

``` shell
#php shell/indexer.php --reindex catalog_url
PHP Fatal error:  Undefined class constant 'STRAIGHT_JOIN_ON' in /app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Select.php on line 276
```
### Test Details

```
Magento Enterprise 1.11.0.0
Nginx
PHP 5.2.17 (Zend Engine v2.2.0)
MySQL 5.0.77
```

**Comment by IvanChepurnyi** [comment]
Try the changes in the following commit. Now it works, haven't checked last time.

**Comment by davidalexander** [comment]
Thanks Ivan. No errors now. I'll post some performance findings when I get a moment.
