### ISSUE TITLE
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION magtoolsdev.ECOMDEV_CLEAN_URL_KEY does 

### ISSUE THREAD

**Issue by caios** [EcomDev/EcomDev_UrlRewrite#6]
Indexer.php fails

Here is the output:

Catalog URL Rewrites index process unknown error:
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION magtoolsdev.ECOMDEV_CLEAN_URL_KEY does                                                       not exist' in /var/www/motamec/webroot/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/motamec/webroot/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/motamec/webroot/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `ecomdev...', Array)
#4 /var/www/motamec/webroot/lib/Varien/Db/Adapter/Pdo/Mysql.php(337): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `ecomdev...', Array)
#5 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Abstract.php(632): Varien_Db_Adapter_Pdo_Mysql->query('UPDATE `ecomdev...', Array)
#6 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(1079): Zend_Db_Adapter_Abstract->update('ecomdev_url                                                      rewr...', Array, Array)
#7 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(1142): EcomDev_UrlRewrite_Model_Mysql4_Indexer->_gen                                                      erateProductUrlKeyIndex(NULL)
#8 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(2160): EcomDev_UrlRewrite_Model_Mysql4_Indexer->_gen                                                      erateProductRequestPathIndex()
#9 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Indexer.php(96): EcomDev_UrlRewrite_Model_Mysql4_Indexer->reindexAll()
#10 /var/www/motamec/webroot/app/code/core/Mage/Index/Model/Process.php(139): EcomDev_UrlRewrite_Model_Indexer->reindexAll()
#11 /var/www/motamec/webroot/app/code/core/Mage/Index/Model/Process.php(167): Mage_Index_Model_Process->reindexAll()
#12 /var/www/motamec/webroot/shell/indexer.php(158): Mage_Index_Model_Process->reindexEverything()
#13 /var/www/motamec/webroot/shell/indexer.php(198): Mage_Shell_Compiler->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION magtoolsdev.ECOMDEV                                                      _CLEAN_URL_KEY does not exist' in /var/www/motamec/webroot/lib/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/motamec/webroot/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `ecomdev...', Array)
#3 /var/www/motamec/webroot/lib/Varien/Db/Adapter/Pdo/Mysql.php(337): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `ecomdev...', Array)
#4 /var/www/motamec/webroot/lib/Zend/Db/Adapter/Abstract.php(632): Varien_Db_Adapter_Pdo_Mysql->query('UPDATE `ecomdev...', Array)
#5 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(1079): Zend_Db_Adapter_Abstract->update('ecomdev_url                                                      rewr...', Array, Array)
#6 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(1142): EcomDev_UrlRewrite_Model_Mysql4_Indexer->_gen                                                      erateProductUrlKeyIndex(NULL)
#7 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Mysql4/Indexer.php(2160): EcomDev_UrlRewrite_Model_Mysql4_Indexer->_gen                                                      erateProductRequestPathIndex()
#8 /var/www/motamec/webroot/app/code/community/EcomDev/UrlRewrite/Model/Indexer.php(96): EcomDev_UrlRewrite_Model_Mysql4_Indexer->reindexAll()
#9 /var/www/motamec/webroot/app/code/core/Mage/Index/Model/Process.php(139): EcomDev_UrlRewrite_Model_Indexer->reindexAll()
#10 /var/www/motamec/webroot/app/code/core/Mage/Index/Model/Process.php(167): Mage_Index_Model_Process->reindexAll()
#11 /var/www/motamec/webroot/shell/indexer.php(158): Mage_Index_Model_Process->reindexEverything()
#12 /var/www/motamec/webroot/shell/indexer.php(198): Mage_Shell_Compiler->run()
#13 {main}

**Comment by IvanChepurnyi** [comment]
This is possible only if you installed extension not on the same DB and when dumped DB haven't included Stored Routings into dump, so they were not imported into new one. The fix is to reinstall the extension on new DB:
1. Drop all ecomdev_urlrewrite_\* tables
2. Delete record from core_resource with code ecomdev_urlrewrite_setup
