### ISSUE TITLE
Honor the 'Use Categories Path for Product URLs' setting

### ISSUE THREAD

**Issue by paales** [EcomDev/EcomDev_UrlRewrite#9]
The setting isn't honored, would be handy though.

We have:
- 800 categories
- 300k products
- ~5 categories / product
- 10 store views ~ 100k visible products per store

This would currently mean that the rewrite table would have `300k * 10 * 5 = 15m rows` (all hidden products are currently added as well).

If issue #8 would be solved and the 'Use Categories Path for Product URLs'  setting is implemented we would have `100k products * 10 = 1m rows`.

Since less rows is always better, this would be a big win.

I could make some modifications to the script my self if you'd be willing to accept a pullrequest?

**Comment by paales** [comment]
Any pointers perhaps where I should look to fix this my self? My tables are getting out of control at this moment (and performance is bad).

**Comment by IvanChepurnyi** [comment]
Try this change. If helps - close the ticket.

**Comment by paales** [comment]
This fixes it!! Thanks!
